[package]
name = "RustyChrom"
version = "0.1.0"
edition = "2021"

[lib]
name = "RustyChrom_lib"
path = "src/lib.rs"

[[bin]]
name = "RustyChrom"
path = "src/bin/bin.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
